In [42]:
import numpy as np

In [43]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

### Implement Mean Absolute Error

In [44]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is: ", total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is: ", mae)

In [45]:
mae(y_predicted, y_true)

Total error is:  2.5
Mean absolute error is:  0.5


In [47]:

def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [48]:
mae_np(y_predicted, y_true)

0.5

### Implement Log Loss or Binary Cross Entropy

In [53]:
np.log([0])

/var/folders/q6/b9hy2b853mgbskhvzkjkqvg40000gn/T/ipykernel_77349/262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [54]:
epsilon = 1e-15

In [55]:
np.log([epsilon])

array([-34.53877639])

In [56]:
y_predicted

array([1, 1, 0, 0, 1])

In [57]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [58]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [60]:
y_predicted_new = np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [62]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [63]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [64]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [65]:
log_loss(y_true, y_predicted)

17.2696280766844